server:
    port: 8080
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    data:
        neo4j:
            uri: bolt://localhost:7687
            username: neo4j
            password: sercet
